module.exports = [
  { readMeTitle : 'Module',
    dataTitle : 'npmName' },
  { readMeTitle : 'Binding',
    dataTitle : 'binding',
    dataType : 'boolean' },
  { readMeTitle : 'Solves SLE',
    dataTitle : 'solvesSLE',
    dataType : 'boolean' },
  { readMeTitle : 'Node.js',
    dataTitle : 'supportsNodejs',
    dataType : 'boolean' },
  { readMeTitle : 'Browser',
    dataTitle : 'supportsBrowser',
    dataType : 'boolean' },
  { readMeTitle : 'Dependants',
    dataTitle : 'dependants',
    dataType : 'number' },
];
